package ultra

import (
	"fmt"
	"strings"
)

// ComposeVar is the app-namespaced launcher variable a secret is passed through
// to reach its container. Namespacing by app keeps the same env name declared by
// two different apps (e.g. DATABASE_URL) from colliding in the shared launcher
// environment.
func ComposeVar(app, name string) string {
	return "ULTRA_" + sanitizeApp(app) + "__" + name
}

// ComposeOverride returns a docker-compose override that maps each of app's
// secret env vars to its namespaced launcher variable via interpolation, e.g.
// `DATABASE_URL: ${ULTRA_WORKER__DATABASE_URL}`. The container sees the real
// name carrying this app's value.
func ComposeOverride(app string, names []string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by ultra from apps/%s/config. References only, no secrets.\n", app)
	b.WriteString("services:\n")
	fmt.Fprintf(&b, "  %s:\n", app)
	b.WriteString("    environment:\n")
	for _, name := range names {
		fmt.Fprintf(&b, "      %s: ${%s}\n", name, ComposeVar(app, name))
	}
	return b.String()
}

// sanitizeApp makes an app name safe for use as an environment variable segment,
// upper-casing it and replacing any character that isn't a letter, digit, or
// underscore.
func sanitizeApp(app string) string {
	var b strings.Builder
	for _, r := range strings.ToUpper(app) {
		if r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '_' {
			b.WriteRune(r)
		} else {
			b.WriteByte('_')
		}
	}
	return b.String()
}
