// Package compose builds the single docker-compose override that forwards every
// app's resolved secrets into its container through app-namespaced launcher
// variables.
package compose

import (
	"fmt"
	"strings"
)

// AppSecrets pairs an app with the secret env-var names its Config declares, and
// is the per-app input to ComposeOverride.
type AppSecrets struct {
	App   string
	Names []string
}

// ComposeVar is the app-namespaced launcher variable a secret is passed through
// to reach its container. Namespacing by app keeps the same env name declared by
// two different apps (e.g. DATABASE_URL) from colliding in the shared launcher
// environment.
func ComposeVar(app, name string) string {
	return "ULTRA_" + sanitizeApp(app) + "__" + name
}

// ComposeOverride returns one docker-compose override that maps every app's
// secret env vars to their namespaced launcher variables via interpolation, e.g.
// `DATABASE_URL: ${ULTRA_WORKER__DATABASE_URL}`, one service block per app. The
// container sees the real name carrying its own app's value.
func ComposeOverride(apps []AppSecrets) string {
	var b strings.Builder
	b.WriteString("# Code generated by ultra. DO NOT EDIT.\n")
	b.WriteString("services:\n")
	for _, app := range apps {
		fmt.Fprintf(&b, "  %s:\n", app.App)
		b.WriteString("    environment:\n")
		for _, name := range app.Names {
			fmt.Fprintf(&b, "      %s: ${%s}\n", name, ComposeVar(app.App, name))
		}
	}
	return b.String()
}

// sanitizeApp makes an app name safe for use as an environment variable segment,
// upper-casing it and replacing any character that isn't a letter, digit, or
// underscore.
func sanitizeApp(app string) string {
	var b strings.Builder
	for _, r := range strings.ToUpper(app) {
		if r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '_' {
			b.WriteRune(r)
		} else {
			b.WriteByte('_')
		}
	}
	return b.String()
}
