// Package compose builds the single docker-compose override that forwards every
// app's resolved secrets into its container through app-namespaced launcher
// variables.
package compose

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"
)

// fingerprintPrefix marks the header line gen stamps into an override recording
// each app's declared-secret fingerprint, so run can tell whether the committed
// file still matches the current Config.
const fingerprintPrefix = "# ultra:fingerprints"

// Fingerprint is a short, stable hash of an app's declared secret names. gen
// stamps it into the override; run recomputes it from the current Config and
// compares, so a changed set of declared secrets marks the override as stale.
func Fingerprint(names []string) string {
	sum := sha256.Sum256([]byte(strings.Join(names, "\n")))
	return hex.EncodeToString(sum[:])[:12]
}

// ParseFingerprints reads the per-app fingerprints gen stamped into an override,
// mapping each app to its declared-secret hash. An override without the header
// yields an empty map, which run treats as stale.
func ParseFingerprints(content string) map[string]string {
	out := map[string]string{}
	for _, line := range strings.Split(content, "\n") {
		if !strings.HasPrefix(line, fingerprintPrefix) {
			continue
		}
		for _, pair := range strings.Fields(strings.TrimPrefix(line, fingerprintPrefix)) {
			if app, hash, ok := strings.Cut(pair, "="); ok {
				out[app] = hash
			}
		}
		break
	}
	return out
}

// AppSecrets pairs an app with the secret env-var names its Config declares, and
// is the per-app input to ComposeOverride.
type AppSecrets struct {
	App   string
	Names []string
}

// Namespace is the sanitized app segment of an app's launcher variables, the
// part shared by every ComposeVar for that app. Two apps with the same
// Namespace forward their secrets through the same launcher variables and would
// collide, even when their raw names (and compose service names) differ.
func Namespace(app string) string {
	return sanitizeApp(app)
}

// ComposeVar is the app-namespaced launcher variable a secret is passed through
// to reach its container. Namespacing by app keeps the same env name declared by
// two different apps (e.g. DATABASE_URL) from colliding in the shared launcher
// environment.
func ComposeVar(app, name string) string {
	return "ULTRA_" + sanitizeApp(app) + "__" + name
}

// ComposeOverride returns one docker-compose override that maps every app's
// secret env vars to their namespaced launcher variables via interpolation, e.g.
// `DATABASE_URL: ${ULTRA_WORKER__DATABASE_URL}`, one service block per app. The
// container sees the real name carrying its own app's value.
func ComposeOverride(apps []AppSecrets) string {
	var b strings.Builder
	b.WriteString("# Code generated by ultra. DO NOT EDIT.\n")
	b.WriteString(fingerprintPrefix)
	for _, app := range apps {
		fmt.Fprintf(&b, " %s=%s", app.App, Fingerprint(app.Names))
	}
	b.WriteString("\n")
	b.WriteString("services:\n")
	for _, app := range apps {
		fmt.Fprintf(&b, "  %s:\n", app.App)
		b.WriteString("    environment:\n")
		for _, name := range app.Names {
			fmt.Fprintf(&b, "      %s: ${%s}\n", name, ComposeVar(app.App, name))
		}
	}
	return b.String()
}

// sanitizeApp makes an app name safe for use as an environment variable segment,
// upper-casing it and replacing any character that isn't a letter, digit, or
// underscore.
func sanitizeApp(app string) string {
	var b strings.Builder
	for _, r := range strings.ToUpper(app) {
		if r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '_' {
			b.WriteRune(r)
		} else {
			b.WriteByte('_')
		}
	}
	return b.String()
}
